import random

FIBBAGE_PROMPTS = [
    {"prompt": "Donald Duck's middle name.", "answer": "Fauntleroy"},
    {"prompt": "A study published in the journal Anthrozoo reported that cows produce 5% more milk when they are given _____.", "answer": "Names"},
    {"prompt": "In 2002, Bruce Willis sent 12,000 boxes of _____ to U.S. soldiers in Afghanistan.", "answer": "Girl Scout Cookies"},
    {"prompt": "The original name for the search engine Google was _____.", "answer": "Backrub"},
    {"prompt": "In the 19th century, it was fashionable for wealthy Europeans to have _____ as pets.", "answer": "Hermits"},
    {"prompt": "In Switzerland, it is illegal to own just one _____.", "answer": "Guinea pig"},
    {"prompt": "A group of flamingos is called a _____.", "answer": "Flamboyance"},
    {"prompt": "The tiny plastic or metal tube at the end of a shoelace is called an _____.", "answer": "Aglet"},
    {"prompt": "The Roman emperor Caligula once declared war on _____.", "answer": "The sea"},
    {"prompt": "Before the 17th century, carrots were _____.", "answer": "Purple"},
    {"prompt": "The dot over the letter 'i' and 'j' is called a _____.", "answer": "Tittle"},
    {"prompt": "The _____ is the national animal of Scotland.", "answer": "Unicorn"},
    {"prompt": "On November 12, 1970, George Thornton, a highway engineer in Oregon, had the unusual job of blowing up a _____.", "answer": "Dead Whale"},
    {"prompt": "People in Damariscotta, Maine hold an annual race where they use _____ as boats.", "answer": "Pumpkins"},
    {"prompt": "As a young student in Buenos Aires, Pope Francis worked as a _____.", "answer": "Bouncer"},
    {"prompt": "A woman in Muncie, Indiana was hospitalized after trying to remove a callus on her foot with a _____.", "answer": "Shotgun"},
    {"prompt": "Jacobite Cruises purchased unusual insurance to protect it from damage caused by _____.", "answer": "The Loch Ness Monster"},
    {"prompt": "El Colacho is a Spanish festival where people dress up like the devil and jump over _____.", "answer": "Babies"},
    {"prompt": "Cheap Chic Weddings is an annual contest in which participants make wedding dresses out of _____.", "answer": "Toilet Paper"},
    {"prompt": "Marcella Hazan is the culinary guru who pioneered the unusual technique of cooking duck with a _____.", "answer": "Hair Dryer"},
    {"prompt": "The sound of E.T. walking was made by someone squishing _____.", "answer": "Jell-O"},
    {"prompt": "The first item listed on eBay was a broken _____.", "answer": "Laser Pointer"},
    {"prompt": "Oddly enough, Albert Einstein's eyeballs can be found in a _____ in New York City.", "answer": "Safe Deposit Box"},
    {"prompt": "In 2013, a wealthy Michigan man bought the house next to his ex-wife and erected a giant bronze statue of a _____.", "answer": "Middle Finger"},
    {"prompt": "The name of the first chimp sent into space.", "answer": "Ham"},
    {"prompt": "The name for a group of porcupines.", "answer": "Prickle"},
    {"prompt": "The name of the dog that won the 2012 World's Ugliest Dog Competition.", "answer": "Mugly"},
    {"prompt": "Dr. Seuss is credited with coining this common derogatory term in his 1950 book If I Ran the Zoo.", "answer": "Nerd"},
    {"prompt": "The name of the man on the Quaker Oats label.", "answer": "Larry"},
    {"prompt": "During a famous fire in 1567, a Norwegian man named Hans Steininger died after tripping over a _____.", "answer": "Beard"},
    {"prompt": "The fishing company E21 makes a very peculiar fishing rod that is composed of 70% _____.", "answer": "Carrots"},
    {"prompt": "On January 13, 2014, U.S. Secretary of State John Kerry presented to Russian Foreign Minister Sergei Lavrov the odd gift of two very large _____.", "answer": "Potatoes"},
    {"prompt": "During the mid to late-nineties, the English town of Glastonbury was on a manhunt for the old house intruder known as 'The _____.'", "answer": "Tickler"},
    {"prompt": "Suffering from an extremely rare side effect after getting hip surgery in 2010, a Dutch man has alienated his family because he cannot stop _____.", "answer": "Laughing"},
    {"prompt": "It's weird work but Jackie Samuel charges $60 an hour to _____.", "answer": "Snuggle"},
    {"prompt": "Huggies Brazil developed a phone app that tells you when a baby's diaper is wet. It's called _____.", "answer": "Tweetpee"},
    {"prompt": "Ben and Jerry only started making ice cream because it was too expensive to make _____.", "answer": "Bagels"},
    {"prompt": "Tashirojima is an island off of Japan that is completely overrun by _____.", "answer": "Cats"},
    {"prompt": "While president of the United States, John Adams had a dog named Juno and a dog named _____.", "answer": "Satan"},
    {"prompt": "In 2012, a 26-year-old man from London went on a mission to lick every _____ in the United Kingdom.", "answer": "Cathedral"},
    {"prompt": "In 2003, Morocco made the highly unusual offer to send 2,000 _____ to assist the United States' war efforts in Iraq.", "answer": "Monkeys"},
    {"prompt": "Romano Mussolini, son of the fascist dictator Benito Mussolini, did not follow in his father's footsteps. Instead, he made his living as a _____.", "answer": "Jazz Musician"},
    {"prompt": "ROAD TRIP! When in Nepal, visit the village of Parsawa and Laxmipur, where you can enjoy the slightly off-putting 10 day _____ Festival.", "answer": "Cursing"},
    {"prompt": "A group known as the 'Robin Hooders' in Keene, New Hampshire pay for other people's _____.", "answer": "Parking Meters"},
    {"prompt": "In an effort to push 'slow TV,' Norway had a 12-hour block of programming in 2013 dedicated to _____.", "answer": "Knitting"},
    {"prompt": "Belmont University in Nashville has offered a class called 'Oh, Look, a _____.'", "answer": "Chicken"},
    {"prompt": "The area in the Pacific Ocean where great white sharks congregate every spring is called the White Shark _____.", "answer": "Cafe"},
    {"prompt": "Reg Mellor is the reigning champion of a sport that just involves keeping a _____ in your pants.", "answer": "Ferret"},
    {"prompt": "Although very unconventional, farmer William von Schneidau feeds his pigs _____.", "answer": "Marijuana"},
    {"prompt": "When Paul Nelson and Andrew Hunter climbed Britain's highest mountain in 2006, they made an unusual discovery hidden behind a pile of stones. It was a _____.", "answer": "Piano"},
    {"prompt": "At 2:45 a.m. one day in June 2013, a man in Orlando, Florida was arrested for walking up to a police officer and punching his _____.", "answer": "Horse"},
    {"prompt": "A 2013 Pakistani game show caused a controversy when their grand prize was a _____.", "answer": "Baby"},
    {"prompt": "In 2013, two teens from Sequoyah High School near Atlanta, Georgia won $5,000 scholarships for wearing _____ to prom.", "answer": "Duct Tape"},
    {"prompt": "Since 2000, a couple in Queens, New York has been living rent-free in a _____ in exchange for taking care of it.", "answer": "Cemetery"},
    {"prompt": "In 2013, a 51-year-old Swedish inmate broke out of prison a day before his scheduled release so he could go see a _____.", "answer": "Dentist"},
    {"prompt": "In 2010, Customs officers on the Norway-Sweden border intercepted a truck trying to smuggle 28 tons of _____ from China.", "answer": "Garlic"},
    {"prompt": "In 2012, a teenager from Weslaco, Texas claimed the reason he stabbed his friend was because a _____ made him do it.", "answer": "Ouija Board"},
    {"prompt": "ROADTRIP! When on a spring break trip to Dongyang, China, be sure to try their eggs cooked in ______.", "answer": "Young Boy Urine"},
    {"prompt": "A man in Milford, Iowa got fired from his job after he used a ____ to dislodge his Twix bar from the office vending machine.", "answer": "Forklift"},
    {"prompt": "According to a Chinese myth, if a vampire comes across a sack of rice, he must ____.", "answer": "Count Each Grain"},
    {"prompt": "When soccer player Stefan Schwarz signed with Sunderland in 1999, the team made sure that his contract specifically prohibited him from traveling to ___.", "answer": "Outer Space"},
    {"prompt": "What Dr. Edgar Parker legally changed his name to, in order to help his dental practice.", "answer": "Painless"},
    {"prompt": "After an allergic reaction to steroids used to treat asthma, a 28-year old woman started growing ____ on her head instead of hair.", "answer": "Fingernails"},
    {"prompt": "PETA has asked officials in Punxsutawney to replace Phil, the Groundhog Day groundhog, with ______.", "answer": "An Animatronic Groundhog"},
    {"prompt": "In 2004, the CEO of Blockbuster mailed Reed Hastings, the CEO of Netflix, an odd package. He sent him a ___.", "answer": "Kitchen Sink"},
    {"prompt": "According to a 2010 study, one child in the U.S. was injured every 46 minutes by a ___.", "answer": "Bounce House"},
    {"prompt": "In October of 2013, eight sixth-graders from a New York college prep school were hospitalized after someone released _____ in a classroom.", "answer": "Axe Body Spray"},
    {"prompt": "In 2013, Dell issued a recall after customers complained their laptops smelled like ____.", "answer": "Cat Urine"},
    {"prompt": "The Kila Raipur Sports Festival, held annually in Punjab, India, has many odd and dangerous events, including one where the participants lay on the ground and get _______.", "answer": "Run Over By A Tractor"},
    {"prompt": "The city of Olney, Illinois organizes an annual event in order to ______ squirrels.", "answer": "Count"},
    {"prompt": "While in Florence, New Jersey be sure to check out the auto repair shop which, according to its owner, has an operational toilet once owned by _____.", "answer": "Hitler"},
    {"prompt": "Amerigo Vespucci, the man for whom America was named, was a _____ dealer.", "answer": "Pickle"},
    {"prompt": "Walter Arnold received the world's first speeding ticket in 1896 for going _____ miles per hour.", "answer": "8"},
    {"prompt": "Edgar Valdez Villarreal, a notorious Mexican drug cartel leader, had the not-so-scary nickname 'La ______'.", "answer": "Barbie"},
    {"prompt": "Frank Hayes is the first jockey to win a race while ______.", "answer": "Dead"},
    {"prompt": "In 1967, a small town in Ecuador elected an inanimate object mayor. The elected mayor was a ______.", "answer": "Foot Powder"},
    {"prompt": "As a way to protest Belarus' police state, a Swedish group dropped hundreds of ________ from an airplane.", "answer": "Teddy Bears"},
    {"prompt": "A man in western Pennsylvania got a DUI for having an open can of beer while riding a ____.", "answer": "Lawn Mower"},
    {"prompt": "Anatidaephobia is the fear that somewhere in the world a _______ is watching you.", "answer": "Duck"},
    {"prompt": "According to a Logitech study, 49% of lost remote controls are found in the couch, while 4% are found in the ____.", "answer": "Fridge"},
    {"prompt": "The French have a pastry called 'Nun's ___'.", "answer": "Fart"},
    {"prompt": "Alexander the Great made his men ________ before a battle.", "answer": "Shave"},
    {"prompt": "Freddie Mercury backed out of a duet with Michael Jackson because Jackson brought a _____ to the recording studio.", "answer": "Llama"},
    {"prompt": "An Indiana woman sued a church cemetery because they refused to install her late husband's tombstone shaped like a _____.", "answer": "Couch"},
    {"prompt": "While in Alliance, Nebraska, you can visit the Stonehenge replica made out of ____.", "answer": "Cars"},
    {"prompt": "A Florida man choked to death on cockroaches he ate while trying to win a ___.", "answer": "Python"},
    {"prompt": "For one day in 1998, Topeka, Kansas renamed itself ______.", "answer": "Topikachu"},
    {"prompt": "There was once a fourth member of Kellogg's Rice Krispies mascot gang: Snap, Crackle, Pop and ____.", "answer": "Pow"},
    {"prompt": "In 2006, the wax museum Madame Tussauds in New York City introduced its first wax ____.", "answer": "Baby"},
    {"prompt": "In 2007, a woman with a rare disorder married the ______.", "answer": "Eiffel Tower"},
    {"prompt": "On his own website, magician David Blaine once wrote, 'The most courageous act a man can do is _____.'", "answer": "Cry"},
    {"prompt": "The University of Victoria offers a physical education class called The Science of ________.", "answer": "Batman"},
    {"prompt": "The Lehigh Valley IronPigs, a minor league baseball team, held a contest where the prize was a voucher for a ______.", "answer": "Funeral"},
    {"prompt": "Every year residents in Ivrea, Italy reenact a historical battle of their region, using ____ instead of weapons.", "answer": "Oranges"},
    {"prompt": "Nigeria's version of Cookie Monster can't stop eating _____.", "answer": "Yams"},
    {"prompt": "Advanced Comfort Technology makes waterbeds for _____.", "answer": "Cows"},
    {"prompt": "Mexico's Isla de las Munecas is an attraction known for having hundreds of ________ hanging in its trees.", "answer": "Dolls"},
    {"prompt": "In 2013, a U.S. Customs and Border Protection Officer was found guilty of granting citizenship in exchange for 200 ____.", "answer": "Egg Rolls"},
    {"prompt": "A British woman was arrested for hijacking a British ferry and yelling, '________!'", "answer": "I'm Jack Sparrow"},
    {"prompt": "In 2013, the Rethink ad agency placed red beer fridges throughout Europe that could only be opened by _______.", "answer": "Canadians"},
    {"prompt": "According to Forbes, the average income for an 'ice cream taster' is $______ a year.", "answer": "56000"},
    {"prompt": "Located near the town of Stanley, there's a small village in England called No _____.", "answer": "Place"},
    {"prompt": "Edwin E. Holmes, a man with very specific interests, wrote the 254-page book 'A History of _______'.", "answer": "Thimbles"},
    {"prompt": "Haribo sells a gummi in Germany that depicts a human butt with _______ growing out of it.", "answer": "Ears"},
    {"prompt": "@blakeshelton tweeted, 'Just fell down and gashed my hand open while running from ______... Don't ask.'", "answer": "An Ostrich"},
    {"prompt": "Over the course of 35 years, artist Scott Weaver has built a replica of San Francisco using over 100,000 ______.", "answer": "Toothpicks"},
    {"prompt": "On October 24th, 2013 a man in Columbus, Georgia ran into his burning home in order to save his ____.", "answer": "Beer"},
    {"prompt": "Unagi Travel is an unusual Japanese travel agency that sends your ______ on vacations.", "answer": "Stuffed Animals"},
    {"prompt": "Scottsdale Community College's sports teams are oddly named the Fighting _____.", "answer": "Artichokes"},
    {"prompt": "During the 2008 Beijing Olympics, sprinter Usain Bolt said that he ended up eating 1,000 _______.", "answer": "McNuggets"},
    {"prompt": "With 88 catches, Canadian Aaron Gregg holds the Guinness World Record for _______ juggling.", "answer": "Chainsaw"},
    {"prompt": "In 1977, Simulations Publications, Inc. published a strangely named board game called After The ______.", "answer": "Holocaust"},
    {"prompt": "Actual warning on Vidal Sassoon hair dryer: 'Do not use while ______.'", "answer": "Sleeping"},
    {"prompt": "Phil Shaw is the founder of the bizarre sport called Extreme _________.", "answer": "Ironing"},
    {"prompt": "On November 25, 2013, a Chinese girl had surgery to remove the unusual growth of a _____ in her ear canal.", "answer": "Dandelion"},
    {"prompt": "According to The Man-Eating Tigers of Sundarbans, tiger urine 'smells sort of like _____.'", "answer": "Buttered Popcorn"},
    {"prompt": "@taylorswift13 Tweeted 'Thank you for tonight, Des Moines. I found endless amounts of _____ on my arms from hugging lots of you.'", "answer": "Glitter"},
    {"prompt": "In 2000, Australia had its largest ever online petition, which called for an end to rising _____ prices.", "answer": "Beer"},
    {"prompt": "The App of Icelanders is a phone app that warns you if the person you're romantically interested in is a ____.", "answer": "Relative"},
    {"prompt": "In school, Sylvester Stallone was voted by his teachers as Most Likely to Go To _____.", "answer": "The Electric Chair"},
    {"prompt": "Although gross, chemist Sir Robert Cheseborough claimed he ate a spoonful of his invention, ______, every day.", "answer": "Vaseline"},
    {"prompt": "The first thing eaten in outer space was ____.", "answer": "Applesauce"},
    {"prompt": "According to the International Code of Disease, code Y92250 is for 'when a patient is injured in an ____.'", "answer": "Art Gallery"},
    {"prompt": "The rare condition known as 'argyria' causes people's skin to _____.", "answer": "Turn Blue"},
    {"prompt": "In India you can buy a cola named Gau Jal that includes the bizarre ingredient _______.", "answer": "Cow Urine"},
    {"prompt": "In a study done by author Stefan Gates, 44% of adults admitted to eating _____.", "answer": "Boogers"},
    {"prompt": "In 2000, a mafia boss in an Italian prison escaped his cell using only _____.", "answer": "Dental Floss"},
    {"prompt": "Located within Kirkland Lake, Ontario, there lies the controversially named village of ____.", "answer": "Swastika"},
    {"prompt": "In the late 17th century, London was victimized by Whipping Tom, who spanked people and screamed '______!'", "answer": "Spanko"},
    {"prompt": "Famed film director Alfred Hitchcock claimed, 'I'm frightened of ______, worse than frightened, they revolt me.'", "answer": "Eggs"},
    {"prompt": "Ruppy the beagle is a very unusual dog because he can ____.", "answer": "Glow In The Dark"},
    {"prompt": "The Snickers candy bar was named after its creator's _____.", "answer": "Horse"},
    {"prompt": "After consuming antifreeze, a Maltese terrier had his life saved when vets gave him ____ to drink.", "answer": "Vodka"},
    {"prompt": "A Brazilian environmental group launched a campaign urging people to pee in ____ to save water.", "answer": "The Shower"},
    {"prompt": "In 2009, a Russian man shocked doctors when he was found to have a 5 cm long _____ growing in his lung.", "answer": "Tree Branch"},
    {"prompt": "The Backyard Brains company sells a device that lets you control _____ with your mobile phone.", "answer": "Cockroaches"},
    {"prompt": "On the northwest tower of Washington National Cathedral, a gargoyle is made to resemble _____.", "answer": "Darth Vader"},
    {"prompt": "Lake Superior State University offers a license to hunt ____.", "answer": "Unicorns"},
    {"prompt": "A man in Northern Ireland got three months in prison for a fire started trying to turn _____ into gold.", "answer": "His Poop"},
    {"prompt": "A study at Tufts University found that people have the ability to point out _____ in a crowd.", "answer": "Mormons"},
    {"prompt": "Economist Ha-Joon Chang insists that the _____ changed the world more than the Internet.", "answer": "Washing Machine"},
    {"prompt": "A man in New York claims to have been happily married for 25 years to Teagan, who is a ____.", "answer": "Mannequin In A Wheelchair"},
    {"prompt": "A New Mexico bill required psychiatrists testifying in court to wear a ____.", "answer": "Wizard's Hat"},
    {"prompt": "UC Irvine brought 6,084 students together in 2012 to break the world record for largest _____ ever.", "answer": "Dodgeball Game"},
    {"prompt": "Highway construction in Iceland was delayed in 2013 because advocates claimed the land was where _____ live.", "answer": "Elves"},
    {"prompt": "When in the North Shore Mountains near Vancouver, be sure to climb the peak called _______ Mountain.", "answer": "Unnecessary"},
    {"prompt": "According to a Barcelona study, 5% of people have no emotional response when they ______.", "answer": "Listen To Music"},
    {"prompt": "In 1726, Mary Toft convinced doctors that she had given birth to _____.", "answer": "Rabbits"},
    {"prompt": "Mohammed Khurshid Hussain is in the Guinness Records because he can ______ very quickly with his nose.", "answer": "Type"},
    {"prompt": "The art piece 'In Orbit' featured two men living in a giant _____ for 10 days.", "answer": "Hamster Wheel"},
    {"prompt": "@SimonCowell Tweeted: 'Still not sure what a ____ is.'", "answer": "Baby Shower"},
    {"prompt": "In 1518, hundreds in Strasbourg were afflicted with a bizarre condition rendering them unable to stop _____.", "answer": "Dancing"},
    {"prompt": "In 2013 a zoo in China attempted to pass off a _____ as an African lion.", "answer": "Large Dog"},
    {"prompt": "A Swedish dishwasher received disability benefits due to his addiction to _____.", "answer": "Heavy Metal Music"},
    {"prompt": "Bill Bennett made news in 2004 when he sold a single, ordinary ______ on eBay.", "answer": "Corn Flake"},
    {"prompt": "During the 1990s, teachers in North Korea were required to know how to ____.", "answer": "Play The Accordion"},
    {"prompt": "Instead of having guard dogs, police in rural Xinjiang Province use ___.", "answer": "Geese"},
    {"prompt": "In 2013, the Romanian government started taxing a previously untaxed group: ____.", "answer": "Witches"},
    {"prompt": "In 2013, University of Tokyo researchers developed a mirror that makes it look like you're _____.", "answer": "Smiling"},
    {"prompt": "Pam Anderson wrote a recipe book titled 'How to Cook Without a ____.'", "answer": "Book"},
    {"prompt": "In 2004, Trane sold pillows in Japan shaped like a _____ to combat loneliness.", "answer": "Woman's Lap"},
    {"prompt": "Actor Eddie Murphy released a dance song in 1982 titled 'Boogie in _____.'", "answer": "Your Butt"},
    {"prompt": "In Laza, Spain, participants pelt each other with muddy rags full of _____.", "answer": "Fire Ants"},
    {"prompt": "In Christchurch, New Zealand, check out the $6 million cathedral made out of ____.", "answer": "Cardboard"},
    {"prompt": "The mountain logo on Toblerone chocolate contains a hidden image of a _____.", "answer": "Bear"},
    {"prompt": "Ahlgrim Acres is a miniature golf course located in an Illinois _____.", "answer": "Funeral Home"},
    {"prompt": "Psycho was the first American movie to show a ____.", "answer": "Toilet Flushing"},
    {"prompt": "Kim Jong Il was once titled 'Highest Incarnation of the Revolutionary Comradely ____.'", "answer": "Love"},
    {"prompt": "Pentheraphobia is the constant fear of your ______.", "answer": "Mother-In-Law"},
    {"prompt": "The real name of the Internet's famous Grumpy Cat is ___.", "answer": "Tardar Sauce"},
    {"prompt": "In autumn 2013, parking lots in England allowed drivers to pay for parking with _____.", "answer": "Chestnuts"},
    {"prompt": "Gloucestershire, England is home to the traditional _____-kicking competition.", "answer": "Shin"},
    {"prompt": "Moviegoers using phones at Prince Charles Cinema in London are escorted out by people dressed as ____.", "answer": "Ninjas"},
    {"prompt": "A robot at the UK Health & Safety Lab goes by the name _____ Larry.", "answer": "Vomiting"},
    {"prompt": "In 1988, George H. W. Bush celebrated Halloween by dressing up as _____.", "answer": "Himself"},
    {"prompt": "Chick & Sophie Major memorial scholarships are awarded to students who are good at _____.", "answer": "Duck Calls"},
    {"prompt": "Chad Orzel wrote the book 'How to Teach _____ to Your Dog.'", "answer": "Physics"},
    {"prompt": "A Florida woman discovered her ______ had been stolen while neighbors watched.", "answer": "Driveway"},
    {"prompt": "Rapper Eminem proved via Twitter that he was surprisingly great at ____.", "answer": "Donkey Kong"},
    {"prompt": "The only dog given rank in the U.S. Armed Forces was named Sergeant _____.", "answer": "Stubby"},
    {"prompt": "The lead singer of the heavy metal band Hatebeak is ____.", "answer": "A Parrot"},
    {"prompt": "The Mariko Aoki phenomenon is the urge to poop while _____.", "answer": "In A Bookstore"},
    {"prompt": "Metrophilia is sexual arousal caused by ___.", "answer": "Poetry"},
    {"prompt": "Secret code name for the 1940s project to invent the microwave oven.", "answer": "Speedy Weenie"},
    {"prompt": "The original name for Pepsi.", "answer": "Brad's Drink"},
    {"prompt": "Oddly named island 180 miles south of New Zealand at 50°36'S 165°58'E.", "answer": "Disappointment Island"},
    {"prompt": "In the U.S., the original name of the game bingo.", "answer": "Beano"},
    {"prompt": "Brand name for cigarettes sold by Enlightened Tobacco in the 1990s.", "answer": "Death"},
    {"prompt": "The name for random symbols used to indicate swearing in comics (#*&%!).", "answer": "Grawlix"},
    {"prompt": "Item that teachers at Mounts Bay Academy in England were banned from using in 2014.", "answer": "Red Pens"},
    {"prompt": "The Michelin Man's official name.", "answer": "Bibendum"},
    {"prompt": "Former first lady Barbara Bush wrote an official apology letter to this fictional character in 1990.", "answer": "Marge Simpson"},
    {"prompt": "What South Africans call traffic lights.", "answer": "Robots"},
    {"prompt": "Samsung started out as a company that made this completely low-tech product.", "answer": "Noodles"},
    {"prompt": "Cap'n Crunch's first name.", "answer": "Horatio"},
    {"prompt": "The original brand name for Kool-Aid.", "answer": "Fruit Smack"},
    {"prompt": "When Milton Bradley first acquired the rights to it, the game Twister was called this.", "answer": "Pretzel"},
    {"prompt": "Dr. Elena Bodnar invented a bra that can also be used as a ____.", "answer": "Gas Mask"},
    {"prompt": "The police department of Kensington apologized for announcing that drunk drivers would be punished with _____.", "answer": "Listening To Nickelback"},
    {"prompt": "Entrepreneur Leo De Watts has made a fortune selling $115 bottles of ____ to China.", "answer": "British Air"},
    {"prompt": "In 2013, police in the Maldives detained a suspect for loitering near a polling station on suspicion of black magic: ____.", "answer": "A Coconut"},
    {"prompt": "'Sphenopalatine ganglioneuralgia' is the medical name for what happens when you have _____.", "answer": "Brain Freeze (Ice Cream Headache)"},
]

def get_random_prompts(count: int = 5, used_prompts=None):
    """Returns unique Fibbage prompts, avoiding repeats until all prompts have been used."""
    if used_prompts is None:
        used_prompts = set()
    available = [p for p in FIBBAGE_PROMPTS if p.get("prompt") not in used_prompts]
    if len(available) < count:
        used_prompts.clear()
        available = list(FIBBAGE_PROMPTS)
    random.shuffle(available)
    selected = available[:count]
    for p in selected:
        used_prompts.add(p.get("prompt", ""))
    return selected
